version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      test-dependencies:
        patterns:
          - "bandit"
          - "pylint"
          - "pytest*"
          - "moviepy"
          - "pillow"
          - "requests-mock"
          - "tox"
        update-types:
          - "major"
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: "docker"
    directory: "."
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
