[tox]
min_version = 4.0
env_list =
    py310
    py311
    py312
    py313
    py314

[testenv]
deps =
    -r requirements.txt
    -r tests/requirements.txt
commands = 
    pylint --ignore=plugins hathor/
    pylint --rcfile .pylintrc.test tests/
    pytest --cov=hathor/ --cov=hathor --cov-fail-under=98 tests/

[pytest]
filterwarnings = error

[coverage:run]
omit =
    # skip plugins
    hathor/plugins/*
