name: Tag build

on:
  push:
    branches:
    - main

jobs:
  tag_build:
    uses: tnoff/github-workflows/.github/workflows/tag.yml@06f676738efdf3f327af0059b3ce0c6f187e1b5c
    with:
      version_file: ./VERSION