name: Coverage Upload

on:
  push:
    branches: [main]

jobs:
  store-coverage:
    uses: tnoff/github-workflows/.github/workflows/coverage-store.yml@ace23270fbc86eea0152c1cd2b186a03d9839072
    with:
      coverage_source: hathor
      install_command: pip install -r requirements.txt -r tests/requirements.txt
      python_version: 3.14
