name: Dependabot Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bump-version:
    permissions:
      contents: write
    uses: tnoff/github-workflows/.github/workflows/bump-version.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      paths: '["pyproject.toml"]'
      version_file: './VERSION'

  # boto3 and friends: all update types
  auto-approve-specific:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      accept_packages: 'yt-dlp'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}

  auto-approve-google:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      accept_packages: 'google-api-python-client '
      allowed_update_types: 'minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}

  # test dependencies: any update type
  auto-approve-test-deps:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      dependency_groups: 'test-dependencies'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}

  # everything else: patch only
  auto-approve-patch:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      allowed_update_types: 'patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}

  auto-approve-ci:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      file_pattern: '.github/workflows/ci.yml'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}
